name = "forward-tg-msg"
main = "_worker.js"
compatibility_date = "2024-10-01"


[vars]
BOT_TOKEN = "你的_Telegram_Bot_Token"
BOT_SECRET = "你的_Telegram_Bot_Secret"
ADMIN_UID = "你的_Telegram_UID"
WEBHOOK_PATH = "/endpoint"
FRAUD_DB_URL = "https://raw.githubusercontent.com/LloydAsp/nfd/main/data/fraud.db"
NOTIFICATION_URL = "https://raw.githubusercontent.com/arlettebrook/arlettebrook/main/nfd/notification.txt"
START_MSG_URL = "https://raw.githubusercontent.com/arlettebrook/arlettebrook/main/nfd/startMessage.md"
ENABLE_NOTIFICATION = "false"
NOTIFY_INTERVAL = "3600000"
